### ISSUE TITLE
i got error

### ISSUE THREAD

**Issue by becle** [aprithul/mediapipe-3d-ar-effect-demo#1]
$ python3 main.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729510536.107929 11848630 gl_context.cc:357] GL version: 2.1 (2.1 ATI-4.14.1), renderer: AMD Radeon Pro 570 OpenGL Engine
W0000 00:00:1729510536.108848 11848630 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1729510536.118771 11848684 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1729510536.143769 11848681 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1729510536.158360 11848630 gl_context.cc:357] GL version: 2.1 (2.1 ATI-4.14.1), renderer: AMD Radeon Pro 570 OpenGL Engine
W0000 00:00:1729510536.186300 11848688 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1729510536.216742 11848687 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
2024-10-21 20:35:36.409 Python[41544:11848630] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/5q/jx5t6lcj1wj5j1337f4jgxv40000gn/T/org.python.python.savedState
Color buffer:  (360, 640, 3)
Depth buffer:  (360, 640)
release camera
W0000 00:00:1729510538.825384 11848683 landmark_projection_calculator.cc:186] Using NORM_RECT without IMAGE_DIMENSIONS is only supported for the square ROI. Provide IMAGE_DIMENSIONS or use PROJECTION_MATRIX.
/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/google/protobuf/symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
Traceback (most recent call last):
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/mediapipe-3d-ar-effect-demo/main.py", line 244, in <module>
    doMr()
  File "/Users/user/mediapipe-3d-ar-effect-demo/main.py", line 221, in doMr
    render.Draw(sunglassEnt)
  File "/Users/user/mediapipe-3d-ar-effect-demo/render.py", line 141, in Draw
    color, depth = addAndDrawRemoveNode(objNode, entity.Transform, RenderFlags.RenderFlags.ALL_SOLID | RenderFlags.RenderFlags.OFFSCREEN)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/render.py", line 98, in addAndDrawRemoveNode
    renderedImgs = _renderer.render(_scene, flags)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/pyrender/renderer.py", line 125, in render
    self._update_context(scene, flags)
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/pyrender/renderer.py", line 755, in _update_context
    texture._add_to_context()
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/pyrender/texture.py", line 184, in _add_to_context
    self._texid = glGenTextures(1)
                  ^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/GL/exceptional.py", line 178, in glGenTextures
    baseFunction( count, textures)
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/mediapipe-3d-ar-effect-demo/.venv/lib/python3.12/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: ("argument 2: TypeError: No array-type handler for type _ctypes.type (value: <cparam 'P' (0x13fee2ca0)>) registered", (1, <cparam 'P' (0x13fee2ca0)>))

**Comment by becle** [comment]
https://github.com/mmatl/pyrender/issues/284
pip install -U PyOpenGL
